### ISSUE TITLE
What are the modification codes for various RNA modification

### ISSUE THREAD

**Issue by Tesdhi** [nanoporetech/modkit#426]
Hello! I'm currently using "modkit bedmethyl tobigwig" for my Nanopore direct RNA-seq datq. For the parameter "--mod-code", I didn't know the corresponding code that can represent different modifications (m5C, m6A_DRACH, inosine_m6A, pseU) as the input for this parameter. Is there any methods to find them?

Thank you!

**Comment by ArtRand** [comment]
Hello @Tesdhi, 

One way to check is to run 
```bash
modkit modbam check-tags --ignore-index --num-reads 100
```
This is essentially the first 100 reads, it will report how many reads have modified base information and which tags. The output tables will be something like what is [shown in the documentation](https://nanoporetech.github.io/modkit/intro_modbam_check_tags.html#modbam-utilities). 

You can also inspect the config.toml for the base modification models you're using. For example:

```bash
$ dorado download --model rna004_130bps_hac@v5.1.0_inosine_m6A@v1
...
$ cat rna004_130bps_hac\@v5.1.0_inosine_m6A\@v1/config.toml
```

```toml
[general]
creation_date = "09/13/2024, 05:33:30"
model = "conv_lstm"

[model_params]
size = 128
kmer_len = 9
num_out = 3

[modbases]
mod_bases = [ "17596", "a",] # <-- these are the modification codes this model will produce probabilities for
offset = 0
reverse_signal = true
base_start_justify = true
mod_long_names_0 = "Inosine"
mod_long_names_1 = "m6A"
chunk_context_0 = 150
chunk_context_1 = 150
kmer_context_bases_0 = 4
kmer_context_bases_1 = 4
motif = "A"
motif_offset = 0

[refinement]
refine_do_rough_rescale = 1
refine_kmer_center_idx = 3
```
